kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sudhams-clusterrole # No Need to specify the namespace for cluster role and rolebinding as it applies for cluster
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sudhams-clusterrolebinding
subjects:
- kind: User
  name: sudhams
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: example-clusterrole
  apiGroup: rbac.authorization.k8s.io
